<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>uk.gov.laa</groupId>
    <artifactId>glad-bom</artifactId>
    <version>3.0.0</version>
    <packaging>pom</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- Platform Versions -->
        <aws.sdk.version>2.54.2</aws.sdk.version>
        <cucumber.version>7.34.7</cucumber.version>
        <spring-cloud-azure.version>7.4.0</spring-cloud-azure.version>
        <immutables.version>2.12.2</immutables.version>
        <gatling.version>3.15.1</gatling.version>
        <poi.version>5.5.1</poi.version>

        <!-- Shared Libraries -->
        <springdoc.version>3.1.0</springdoc.version>
        <playwright.version>1.62.0</playwright.version>
        <axe.version>4.13.0</axe.version>
        <swagger-annotations.version>2.2.54</swagger-annotations.version>
    </properties>

    <dependencyManagement>
        <dependencies>

            <!-- Apache POI -->
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi</artifactId>
                <version>${poi.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml</artifactId>
                <version>${poi.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml-full</artifactId>
                <version>${poi.version}</version>
            </dependency>

            <!-- AWS -->
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>bom</artifactId>
                <version>${aws.sdk.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Azure -->
            <dependency>
                <groupId>com.azure.spring</groupId>
                <artifactId>spring-cloud-azure-dependencies</artifactId>
                <version>${spring-cloud-azure.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Cucumber -->
            <dependency>
                <groupId>io.cucumber</groupId>
                <artifactId>cucumber-bom</artifactId>
                <version>${cucumber.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Gatling -->
            <dependency>
                <groupId>io.gatling</groupId>
                <artifactId>gatling-test-framework</artifactId>
                <version>${gatling.version}</version>
            </dependency>

            <dependency>
                <groupId>io.gatling</groupId>
                <artifactId>gatling-core-java</artifactId>
                <version>${gatling.version}</version>
            </dependency>

            <dependency>
                <groupId>io.gatling</groupId>
                <artifactId>gatling-http-java</artifactId>
                <version>${gatling.version}</version>
            </dependency>

            <dependency>
                <groupId>io.gatling.highcharts</groupId>
                <artifactId>gatling-charts-highcharts</artifactId>
                <version>${gatling.version}</version>
            </dependency>

            <!-- Immutables runtime annotations -->
            <dependency>
                <groupId>org.immutables</groupId>
                <artifactId>value-annotations</artifactId>
                <version>${immutables.version}</version>
            </dependency>

            <!-- OpenAPI -->
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${springdoc.version}</version>
            </dependency>

            <!-- Shared Test Dependencies -->
            <dependency>
                <groupId>com.microsoft.playwright</groupId>
                <artifactId>playwright</artifactId>
                <version>${playwright.version}</version>
            </dependency>

            <dependency>
                <groupId>com.deque.html.axe-core</groupId>
                <artifactId>playwright</artifactId>
                <version>${axe.version}</version>
            </dependency>

            <!-- Swagger -->
            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-annotations</artifactId>
                <version>${swagger-annotations.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <distributionManagement>
        <repository>
            <id>github</id>
            <url>https://maven.pkg.github.com/ministryofjustice/glad-platform</url>
        </repository>
    </distributionManagement>

</project>